group: Pre-release checks
depends_on:
  - forge
steps:
  - label: "Check release blockers"
    key: check-release-blockers
    job_env: forge
    instance_type: small_branch
    commands:
      - bazel build --build_python_zip //ci/ray_ci/automation:update_version
      - bash -i .buildkite/release-automation/test.sh
